### ISSUE TITLE
Instantly crashes on start

### ISSUE THREAD

**Issue by Krum3L** [beat-saber-modding-group/BeatSaberModInstaller#66]
I cant even open the beat saber mod manager, because it crashes on startup.
Using windows 10 and it worked a while ago

**Comment by Krylke** [comment]
same here

**Comment by megalon** [comment]
Does it crash with an error message, or does it simply doesn't open at all?
It might be getting blocked by your anti virus. If that's the cast, try downloading the classic edition
https://github.com/beat-saber-modding-group/BeatSaberModInstaller/releases/download/v3.6.1/BeatSaberModManagerClassic.exe

**Comment by Krum3L** [comment]
Ill doubt that my antivirus blocks it, since it worked before and its not getting flagged.
It just stops reacting on startup, cant press anything just freezes and a couple of seconds later it just crashes.
Looked for another mod manager and the Classic one works.

**Comment by zerosquared** [comment]
Same here.  It opens for about one second then closes with no message or error...even ran as administrator.  I tried Compatibility mode just to test and it didn't help.

**Comment by eytukan8625** [comment]
I'm having the same issue, and for some reason the classic edition is also giving me issues. I am unable to install any mods, I always get an error, but I can't see what it is because the window cuts it off.

**Comment by sparks3800** [comment]
I have the same problem, here's the call stack from event viewer.

Application: BeatSaberModManager.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at SemVer.Version..ctor(System.String, Boolean)
   at BeatSaberModManager.Core.RemoteLogic.CreateRelease(BeatSaberModManager.DataModels.ReleaseInfo)
   at BeatSaberModManager.Core.RemoteLogic.PopulateReleases()
   at BeatSaberModManager.FormMain.RemoteLoad()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
